name: API CI

on:
  push:
    branches: [main]
    paths:
      - "apps/api/**"
      - "packages/eslint-config/**"
      - "package.json"
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    needs: [prepare]
    runs-on: ubuntu-latest
    if: ${{ needs.prepare.outputs.web_changed == 'true' }}
    strategy:
      matrix:
        test: ["lint", "type-check"]
    defaults:
      run:
        working-directory: apps/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/prepare-install

      - name: Run Test
        run: npm run ${{ matrix.test }}

  test-results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [api-static-test]
    steps:
      - run: exit 1
        if: >-
          ${{
            contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
          }}
