name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.detect_changes.outputs.web_changed }}
      api_changed: ${{ steps.detect_changes.outputs.api_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.*"

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm キャッシュファイルは、Linux/macOS では `~/.npm` に保存される。
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm ci

      - name: Detect changed files
        id: detect_changes
        run: |
          git fetch origin main
          web_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^apps/web/' || echo "")
          api_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^apps/api/' || echo "")
          echo "web_changed=${web_changed}" >> $GITHUB_ENV
          echo "api_changed=${api_changed}" >> $GITHUB_ENV

  web-ci:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.web_changed != '' }}
    steps:
      - name: Cache Next.js build
        id: cache-next
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Lint web
        run: npm run lint -w apps/web

      - name: Run build
        run: npm run build -w apps/api

  lint-api:
    needs: setup
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.api_changed != '' }}
    steps:
      - name: Lint api
        run: npm run lint -w apps/api

      - name: Run build
        run: npm run build -w apps/api
