name: Web CI

on:
  push:
    paths:
      - "apps/web/**"
      - "packages/eslint-config/**"
      - "package.json"
    branches: [main]
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/eslint-config/**"
      - "package.json"
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: apps/web

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/prepare-install

      - name: Cache Next.js build
        id: cache-next
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Run Lint
        run: npm run build

  web-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/prepare-install

      - name: Run Lint
        run: npm run lint
